/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Elementos;

import ComponentesUI.SpeechBubbleDirection;
import java.awt.Color;
import java.text.DecimalFormat;
import java.text.NumberFormat;

/**
 *
 * @author guest
 */
public class TransferenciaBubble extends javax.swing.JPanel {

    /**
     * Creates new form TransferenciaBubble
     */
    public TransferenciaBubble(double valor) {
        initComponents();
        NumberFormat formatter = new DecimalFormat("#0.000");
        jLabel2.setText("$" +formatter.format(valor));
    }
    public void setSent() {
        tRSpeechBubble1.setBackground(new Color(245,127,23));
        tRSpeechBubble1.setDirection(SpeechBubbleDirection.RIGHT);
        jLabel1.setForeground(Color.white);
        jLabel2.setForeground(Color.white);
        jLabel1.setText("Transferiste");
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8_currency_exchange_48px_white.png"))); // NOI18N
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tRSpeechBubble1 = new ComponentesUI.TRSpeechBubble();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tRSpeechBubble1.setBackground(new java.awt.Color(255, 255, 255));
        tRSpeechBubble1.setBorderRadius(30);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(112, 112, 112));
        jLabel1.setText("Te transfirieron");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 112, 112));
        jLabel2.setText("$10.000");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8_currency_exchange_48px.png"))); // NOI18N

        javax.swing.GroupLayout tRSpeechBubble1Layout = new javax.swing.GroupLayout(tRSpeechBubble1);
        tRSpeechBubble1.setLayout(tRSpeechBubble1Layout);
        tRSpeechBubble1Layout.setHorizontalGroup(
            tRSpeechBubble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tRSpeechBubble1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(tRSpeechBubble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        tRSpeechBubble1Layout.setVerticalGroup(
            tRSpeechBubble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tRSpeechBubble1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(tRSpeechBubble1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(tRSpeechBubble1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tRSpeechBubble1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tRSpeechBubble1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private ComponentesUI.TRSpeechBubble tRSpeechBubble1;
    // End of variables declaration//GEN-END:variables

    private Object DecimalFormat(String string) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
