/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ComponentesUI;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author guest
 */
public final class SlidePanel extends javax.swing.JPanel {

    Timer tm;
    int x = 0;
    ArrayList<String> images;

    /**
     * Creates new form SlidePanel
     */
    public SlidePanel(ArrayList<String> list) {
        initComponents();
        this.images = list;
        initSlide(list);
        //SetImageSize(0);
    }

    public void SetImageSize(int i) {
        try {
            ImageIcon icon = new ImageIcon(getClass().getResource(images.get(i)));
            jLabel1.setIcon(icon);
        } catch (Exception e) {
            ImageIcon icon = new ImageIcon(getClass().getResource(images.get(0)));
            jLabel1.setIcon(icon);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8_forward_48px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 50, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/icons8_back_48px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/slide1.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 597, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if (x < 0) {
            x = images.size();
        } else {
            x = x - 1;
        }
        SetImageSize(x);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.out.println(x);
        if (x >= images.size()) {
            x = 0;
        } else {
            x = x + 1;
        }
        SetImageSize(x);
    }//GEN-LAST:event_jLabel3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    public void initSlide(ArrayList<String> list) {
        this.images = list;
        tm = new Timer(5000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SetImageSize(x);
                x += 1;
                if (x >= list.size()) {
                    x = 0;
                } else if (x <= 0) {
                    x = list.size();
                }
            }
        });
        tm.start();
    }
}
