/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panels;

import Objetos.Transaccion;
import Objetos.Usuario;
import UI.Elementos.Header;
import UI.Elementos.TransaccionesInfo;
import UI.Elementos.TransferenciaBubble;
import static Utils.FileUtils.readFile;
import com.google.gson.Gson;
import java.awt.Color;
import java.util.Base64;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author guest
 */
public class History extends javax.swing.JPanel {

    /**
     * Creates new form History
     */
    public History(Usuario u) {
        initComponents();
        jPanel1.setLayout(new MigLayout("fillx"));
        jPanel1.add(new Header("Mi historial"), "wrap, w 572");
        jPanel1.setBackground(Color.white);
        jPanel1.repaint();
        jPanel1.revalidate();
        String file1 = readFile("transacciones.json");

        if (file1 != "") {
            Gson g = new Gson();
            Transaccion[] o = g.fromJson(file1, Transaccion[].class);
            for (Transaccion t : o) {
                if(t.destinatario.equals(u.getBilletera().id)) {
                    addLeft(new TransferenciaBubble(t.monto));
                } else if (t.remitente.equals(u.getBilletera().id)){
                    addRight(new TransferenciaBubble(t.monto));
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addLeft(TransferenciaBubble transferenciaBubble) {
        jPanel1.add(transferenciaBubble, "wrap");
        jPanel1.setBackground(Color.white);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    private void addRight(TransferenciaBubble transferenciaBubble) {
        transferenciaBubble.setSent();
        jPanel1.add(transferenciaBubble, "wrap, al right");
        jPanel1.setBackground(Color.white);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

}
