/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Panels;

import Estructura.Grafo;
import Objetos.Billetera;
import Objetos.Usuario;
import UI.Elementos.BilleteraInfo;
import UI.Elementos.HeaderBilleteras;
import java.awt.Color;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author guest
 */
public class MyWallets extends javax.swing.JPanel {

    /**
     * Creates new form MyWallets
     */
    public MyWallets(Usuario u, Grafo g) {
        initComponents();
        jPanel1.setLayout(new MigLayout("fillx"));
        jPanel1.add(new HeaderBilleteras(u, g), "wrap, w 572");
        jPanel1.setBackground(Color.white);
        jPanel1.repaint();
        jPanel1.revalidate();
        for (Billetera b : u.getBilleteras()) {
            addBilleteras(new BilleteraInfo(b.saldo, b.id));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        jScrollPane1.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addBilleteras(BilleteraInfo billeteraInfo) {
        jPanel1.add(billeteraInfo, "wrap, w 572");
        jPanel1.setBackground(Color.white);
        jPanel1.repaint();
        jPanel1.revalidate();
    }
}
